import Link from 'next/link';
import { ArrowUpRight, Check } from 'lucide-react';
import { expertise } from '@/content/expertise';
import { pageMetadata } from '@/lib/pageMetadata';

export const metadata = pageMetadata('Expertise', 'Performance strategy, workload modelling, test automation, observability, bottleneck analysis, and release-readiness expertise.', '/expertise/');

const workflow=[['Discover','Define critical journeys, service-level expectations, data needs, and operational risk.'],['Model','Translate real traffic, concurrency, pacing, and growth assumptions into defensible workloads.'],['Engineer','Build maintainable scripts, environments, pipeline gates, and production-like test scenarios.'],['Observe','Correlate response time and throughput with application, database, infrastructure, and log signals.'],['Decide','Convert evidence into prioritised findings, capacity guidance, and release recommendations.']];

export default function ExpertisePage(){return <section className="py-20"><p className="eyebrow">Expertise</p><h1 className="section-title mt-5">A practical toolkit for reliable, scalable systems.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-400">Performance engineering is not a single load test. It is a connected discipline spanning discovery, test design, automation, observability, diagnosis, and communication.</p><div className="mt-14 grid gap-5 md:grid-cols-2">{expertise.map((g,index)=><article key={g.group} className="glass-card p-7"><div className="flex items-center justify-between"><span className="text-xs text-cyan-400">0{index+1}</span><span className="text-xs text-slate-600">{g.items.length} capabilities</span></div><h2 className="mt-8 text-2xl font-semibold text-white">{g.group}</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{g.items.map(i=><li key={i} className="flex items-center gap-2 text-sm text-slate-400"><Check className="h-4 w-4 text-cyan-400"/>{i}</li>)}</ul></article>)}</div><div className="mt-24"><p className="eyebrow">Working model</p><h2 className="section-title mt-5">From question to confidence.</h2><div className="mt-10 grid gap-3 lg:grid-cols-5">{workflow.map(([title,text],i)=><article key={title} className="border-t border-cyan-400/40 pt-5"><span className="text-xs text-slate-600">0{i+1}</span><h3 className="mt-6 font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></article>)}</div></div><Link href="/contact" className="button-primary mt-14">Discuss an engineering challenge <ArrowUpRight className="h-4 w-4"/></Link></section>}
