import Link from 'next/link';
import { ArrowUpRight, Linkedin, Mail, MapPin, MessageSquareText } from 'lucide-react';
import { ContactForm } from '@/components/contact/ContactForm';
import { profile } from '@/content/profile';

const topics = ['Performance strategy and test governance', 'JMeter or LoadRunner modernisation', 'Logo design and brand identity', 'Pamphlet, cover, sticker, and packaging design', 'Interior and exterior design concepts', 'Website creation and Android app development'];

export default function Contact() {
  return <section className="py-20"><p className="eyebrow">Contact Krishna Chandra</p><div className="mt-5 grid gap-14 lg:grid-cols-[.9fr_1.1fr]"><div className="flex h-full flex-col"><h1 className="section-title">Let us make the next release easier to trust.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-400">For professional opportunities, consulting conversations, creative and digital service enquiries, or collaboration, send an email or connect through LinkedIn.</p><div className="mt-8 space-y-3 text-sm text-slate-400"><p className="flex items-center gap-3"><MapPin className="h-4 w-4 text-cyan-400" />{profile.location}</p><p className="flex items-center gap-3"><MessageSquareText className="h-4 w-4 text-cyan-400" />English / Hindi</p></div><aside className="mt-10 flex-1 glass-card p-7"><p className="text-xs uppercase tracking-[.2em] text-cyan-400">Good reasons to reach out</p><ul className="mt-7 divide-y divide-white/10">{topics.map((topic, index) => <li key={topic} className="flex gap-4 py-4 text-slate-300"><span className="text-xs text-slate-600">{String(index + 1).padStart(2, '0')}</span>{topic}</li>)}</ul><p className="mt-6 text-sm leading-6 text-slate-500">A useful first message includes the system context, the performance challenge, and the outcome you need.</p></aside></div><div className="glass-card h-full p-7 md:p-8"><p className="eyebrow">Start a conversation</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-white">Send a message</h2><p className="mt-3 leading-7 text-slate-400">Share a few details and we will reply using the email address you provide.</p><div className="mt-8 border-t border-white/10 pt-8"><ContactForm /></div><div className="mt-8 flex flex-wrap gap-3 border-t border-white/10 pt-8"><a href={`mailto:${profile.email}`} className="button-primary"><Mail className="h-4 w-4" />Email Krishna Chandra</a><a href={profile.linkedin} target="_blank" rel="noreferrer" className="button-secondary"><Linkedin className="h-4 w-4" />Krishna Chandra on LinkedIn <ArrowUpRight className="h-4 w-4" /></a></div></div></div><div className="mt-10 border-t border-white/10 pt-8"><p className="text-slate-400">Prefer to explore first?</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/projects/" className="button-secondary">View case studies</Link><Link href="/insights/" className="button-secondary">Read field notes</Link></div></div></section>;
}
