import type { Experience } from '@/types/experience';

export const experience: Experience[] = [
  { company: 'Infinite Computer Solutions', role: 'Assistant Manager', period: 'Jul 2026 — Present', location: 'Gurugram, India', summary: 'Leading performance engineering initiatives for enterprise systems, with responsibility spanning strategy, workload design, execution governance, diagnosis, and stakeholder communication.', responsibilities: ['Performance strategy and workload modelling', 'Non-functional test governance', 'Cross-layer bottleneck analysis and reporting'], tools: ['JMeter', 'LoadRunner', 'Python', 'APM'] },
  { company: 'Oracle', role: 'Senior Application Software Engineer', period: 'Apr 2026 — Jun 2026', location: 'Bengaluru, India', summary: 'Drove performance engineering initiatives for enterprise healthcare applications, focusing on scalability, benchmarking, automation, and high-volume system reliability.', responsibilities: ['Enterprise healthcare performance engineering', 'Scalability validation and benchmarking', 'Automation-led analysis and reporting'], tools: ['JMeter', 'LoadRunner', 'Oracle Enterprise Manager', 'SQL'] },
  { company: 'Oracle', role: 'Application Developer 3', period: 'Oct 2024 — Mar 2026', location: 'Bengaluru, India', summary: 'Engineered and analysed non-functional tests for enterprise applications, correlating application behaviour with database, infrastructure, and monitoring evidence.', responsibilities: ['Load, stress, and endurance testing', 'API benchmarking and root-cause analysis', 'Performance tuning support'], tools: ['JMeter', 'LoadRunner', 'Linux', 'APM'] },
  { company: 'ITC Infotech', role: 'Lead Consultant', period: 'Feb 2022 — Sep 2024', location: 'Bengaluru, India', summary: 'Led performance delivery for investment-platform services, including a large-scale LoadRunner-to-JMeter migration and test automation initiatives.', responsibilities: ['Non-functional testing for Sonata services', 'Citrix performance validation', 'Client reporting and delivery leadership'], tools: ['JMeter', 'LoadRunner', 'Citrix', 'Jenkins'] },
  { company: 'R Systems', role: 'Senior Software Engineer-QC', period: 'Nov 2019 — Feb 2022', location: 'Noida, India', summary: 'Engineered performance tests for web and native applications across oil & gas drilling and credit-card platforms.', responsibilities: ['Scenario and script design', 'Web and native-app performance testing', 'Analysis and client communication'], tools: ['JMeter', 'SQL', 'Monitoring'] },
  { company: 'Cavisson Systems, Inc.', role: 'Senior Software Engineer', period: 'Jul 2019 — Oct 2019', location: 'Noida, India', summary: 'Led performance validation and real-time analysis for customer-facing aviation systems.', responsibilities: ['Server configuration and monitoring', 'API performance testing', 'Client reporting and RCA'], tools: ['JMeter', 'NetStorm', 'Linux'] },
  { company: 'Cavisson Systems, Inc.', role: 'Software Engineer', period: 'Mar 2016 — Jun 2019', location: 'Noida, India', summary: 'Delivered performance engineering across large retail and aviation programmes, including cloud movement, capacity planning, and release validation.', responsibilities: ['Cloud capacity validation', 'Build and release testing', 'Production monitoring and bottleneck analysis'], tools: ['JMeter', 'Redis', 'MongoDB', 'Solr', 'HAProxy'] },
  { company: 'Cavisson Systems, Inc.', role: 'Associate Software Engineer', period: 'Sep 2015 — Feb 2016', location: 'Noida, India', summary: 'Built foundations in non-functional testing, REST service analysis, server monitoring, and technical result reporting.', responsibilities: ['REST request and response analysis', 'Non-functional test execution', 'Server monitoring and reporting'], tools: ['JMeter', 'REST APIs', 'Linux'] },
];
