export type Insight = { slug:string; title:string; summary:string; readTime:string; sections:{heading:string;body:string;points?:string[]}[] };
export const insights: Insight[] = [
  { slug:'performance-testing-strategy', title:'Building a practical performance testing strategy', summary:'A field-tested approach to requirements, workload modelling, execution, monitoring, and reporting.', readTime:'7 min read', sections:[
    {heading:'Start with business risk',body:'A useful strategy begins with the customer journeys and business moments that cannot afford to slow down. Establish service-level expectations, peak events, growth forecasts, dependency constraints, and the cost of failure before choosing a tool.',points:['Identify critical user journeys','Agree measurable response-time and throughput targets','Document peak, average, and growth assumptions']},
    {heading:'Model behaviour, not just volume',body:'Concurrency alone rarely describes a production workload. Account for arrival patterns, pacing, think time, data variation, caching, session behaviour, and the distribution of transactions. A defensible workload model makes every later result easier to trust.'},
    {heading:'Observe the whole system',body:'Response time shows that a problem exists; correlated telemetry explains why. Capture application, database, infrastructure, network, and log signals on the same timeline as the load test.',points:['Synchronise clocks and test markers','Baseline healthy behaviour first','Separate symptoms from resource saturation and contention']},
    {heading:'End with a decision',body:'A report should state what was tested, what happened, why it happened, the risk it creates, and the next action. A release recommendation backed by traceable evidence is more valuable than a folder of charts.'}
  ]},
  { slug:'jmeter-enterprise-readiness', title:'Taking JMeter from scripts to enterprise readiness', summary:'How governance, data strategy, CI/CD, and analysis turn scripts into an engineering capability.', readTime:'6 min read', sections:[
    {heading:'Treat scripts as software',body:'Version control, code review, naming standards, modular components, and repeatable test data are the foundation. This reduces maintenance cost and makes behaviour explainable across teams.'},
    {heading:'Design for distributed execution',body:'Separate orchestration from load generation, validate generator health, and make capacity observable. The test harness must not become the bottleneck it is trying to find.',points:['Use non-GUI execution','Monitor load generators','Keep result collection intentional and lightweight']},
    {heading:'Build a pipeline, not a button',body:'Integrate environment checks, data preparation, execution, result publication, and cleanup into CI/CD. Parameterise workloads and keep secrets outside the test assets.'},
    {heading:'Make trends visible',body:'Individual runs answer a narrow question. Historical comparison exposes regressions, variability, and capacity movement. Store a compact set of meaningful metrics and connect changes back to builds and configuration.'}
  ]},
  { slug:'root-cause-analysis-under-load', title:'Root-cause analysis when the system is under load', summary:'A disciplined way to move from a response-time symptom to the constrained resource or dependency.', readTime:'8 min read', sections:[
    {heading:'Build a shared timeline',body:'Align load events, deployments, logs, traces, and infrastructure metrics. Mark ramps, steady-state windows, failures, and recovery so every team investigates the same period.'},
    {heading:'Follow the constraint',body:'Look for saturation, queueing, contention, and errors—not just high utilisation. A busy resource may be healthy; the constraint is the component that limits useful throughput or increases wait time.'},
    {heading:'Test the hypothesis',body:'Change one meaningful variable and rerun a focused experiment. A credible root cause predicts behaviour: removing or moving the constraint should create a measurable change.',points:['State the hypothesis before changing the system','Keep workload and data comparable','Record configuration with every result']},
    {heading:'Close the loop',body:'Document the causal chain, remediation, evidence, residual risk, and follow-up guardrail. The best RCA also makes the next occurrence easier to detect.'}
  ]}
];
