import type { Project } from '@/types/project';

export const projects: Project[] = [
  {
    slug: 'bravura-solution-sonata',
    title: 'Bravura Solution - Sonata',
    category: 'Asset Maintenance',
    status: 'Delivered',
    period: 'Mar 2022 - Sep 2024',
    organization: 'ITC Infotech',
    summary: 'Performance engineering and automation for Sonata services and Citrix-based asset-maintenance applications.',
    problem: 'The programme required broad non-functional coverage, dependable client reporting, and the migration of existing LoadRunner service scripts to a scalable open-source toolchain.',
    solution: 'Executed multiple non-functional test types, migrated Sonata services from LoadRunner to JMeter, validated Citrix applications, and introduced automation to reduce repetitive effort.',
    stack: ['LoadRunner', 'JMeter', 'Citrix', 'Jenkins', 'JIRA'],
    features: ['Performed non-functional tests across multiple performance scenarios', 'Led the migration of Sonata service scripts from LoadRunner to JMeter', 'Tested asset-maintenance services and Citrix applications', 'Spearheaded automation initiatives to reduce execution time', 'Led daily client meetings and communicated project status', 'Produced detailed, decision-ready test reports'],
  },
  {
    slug: 'moblize',
    title: 'Moblize',
    category: 'Oil & Gas',
    status: 'Delivered',
    period: 'Mar 2020 - Feb 2022',
    organization: 'R Systems',
    summary: 'Performance validation for web and native applications serving the oil and gas drilling domain.',
    problem: 'Web and native applications required consistent performance evaluation and clear stakeholder visibility across ongoing releases.',
    solution: 'Built and executed JMeter workloads, assessed application behaviour, maintained project communication, and delivered detailed performance reports.',
    stack: ['JMeter', 'JIRA', 'Web Testing', 'Native App Testing'],
    features: ['Executed diverse non-functional tests with JMeter', 'Tested both web applications and native applications', 'Participated in daily client meetings and status reviews', 'Generated detailed reports for transparent decision-making'],
  },
  {
    slug: 'flyers',
    title: 'Flyers',
    category: 'Financial Services',
    status: 'Delivered',
    period: 'Nov 2019 - Mar 2020',
    organization: 'R Systems',
    summary: 'Non-functional performance assessment and stakeholder reporting for a customer-facing platform.',
    problem: 'The application required structured performance validation and dependable communication of results to client stakeholders.',
    solution: 'Conducted JMeter-based non-functional tests, shared daily project insights, and produced comprehensive reports.',
    stack: ['JMeter', 'JIRA', 'Performance Reporting'],
    features: ['Conducted multiple non-functional test types with JMeter', 'Provided daily project status and technical insights', 'Produced comprehensive client-facing test reports'],
  },
  {
    slug: 'kra-indigo-airlines',
    title: 'KRA - Indigo Airlines',
    category: 'Aviation',
    status: 'Delivered',
    period: 'Mar 2019 - Jul 2019',
    organization: 'Cavisson Systems, Inc.',
    summary: 'Server performance, API testing, live issue analysis, and reporting for an aviation platform.',
    problem: 'The platform needed reliable server operation, broad non-functional coverage, and rapid diagnosis of issues under realistic load.',
    solution: 'Configured and monitored servers, executed JMeter API and performance tests, performed real-time RCA, and presented findings to client teams.',
    stack: ['JMeter', 'MySQL', 'Linux', 'API Testing'],
    features: ['Configured and maintained servers', 'Implemented a comprehensive non-functional test suite', 'Performed real-time issue analysis and root-cause analysis', 'Conducted API testing with JMeter', 'Led daily client meetings and project updates', 'Produced detailed performance reports'],
  },
  {
    slug: 'mosaic-kohls',
    title: 'MOSAIC - KOHLS Corporation',
    category: 'Retail & E-commerce',
    status: 'Delivered',
    period: 'Jun 2017 - Mar 2019',
    organization: 'Cavisson Systems, Inc.',
    summary: 'Performance engineering, DevOps collaboration, and production monitoring for a large retail platform.',
    problem: 'A high-volume retail estate required continuous performance validation across releases, production monitoring, and fast cross-team issue resolution.',
    solution: 'Executed non-functional and API tests, supported hotfix and release deployments, monitored server health, and delivered real-time RCA and client reporting.',
    stack: ['AKAMAI Luna', 'MySQL', 'JMeter', 'DevOps', 'API Testing'],
    features: ['Configured and maintained performance environments', 'Executed comprehensive non-functional tests', 'Performed real-time RCA for production issues', 'Collaborated on hotfix and release deployments', 'Conducted build, release, and API testing', 'Led client status meetings and reporting', 'Monitored servers and identified bottlenecks'],
  },
  {
    slug: 'kos-kohls',
    title: 'KOS - KOHLS Corporation',
    category: 'Cloud & Retail',
    status: 'Delivered',
    period: 'Mar 2017 - Jun 2017',
    organization: 'Cavisson Systems, Inc.',
    summary: 'Cloud-movement readiness, capacity planning, and load validation for a distributed retail architecture.',
    problem: 'A newly established cloud architecture needed capacity evidence and performance validation before transition.',
    solution: 'Defined cloud-movement steps, determined server capacity, validated the new technology stack, and executed load operations.',
    stack: ['JMeter', 'AKAMAI Luna', 'Node.js', 'Redis', 'MongoDB', 'Solr', 'MySQL', 'HAProxy'],
    features: ['Established critical steps for cloud movement', 'Determined server capacity against workload demand', 'Validated Node.js, Redis, MongoDB, Solr, MySQL, and HAProxy architecture', 'Conducted load operations and performance tests'],
  },
  {
    slug: 'atg-kohls',
    title: 'Art Technology Group - KOHLS Corporation',
    category: 'Retail & E-commerce',
    status: 'Delivered',
    period: 'Sep 2015 - Mar 2017',
    organization: 'Cavisson Systems, Inc.',
    summary: 'REST service testing, non-functional validation, production monitoring, and root-cause analysis.',
    problem: 'The retail platform required ongoing server supervision, API-level performance insight, and clear identification of production risk.',
    solution: 'Analysed REST requests and responses, maintained server configurations, executed JMeter tests, monitored production alerts, and reported findings.',
    stack: ['JMeter', 'AKAMAI Luna', 'REST APIs', 'Linux'],
    features: ['Analysed REST service requests and responses', 'Supported server configuration and maintenance', 'Implemented multiple non-functional test types using JMeter', 'Provided root-cause analysis', 'Monitored production sites and server alerts', 'Created client-facing test reports'],
  },
];
