export const siteMetadata = {
  title: 'Krishna Chandra | Performance Engineering, Design & Digital Solutions',
  description:
    'Krishna Chandra delivers performance engineering, load testing, observability, creative design, website creation and Android app development.',
  url: 'https://krishnachandra.com',
  keywords: [
    'Krishna Chandra',
    'performance engineering',
    'performance testing',
    'load testing',
    'JMeter',
    'LoadRunner',
    'scalability testing',
    'capacity planning',
    'observability',
    'root cause analysis',
    'test automation',
    'cloud readiness',
    'performance tuning',
    'Oracle Inform Suite',
    'logo design',
    'brand identity design',
    'pamphlet design',
    'interior design',
    'exterior design',
    'website creation',
    'web development',
    'Android app development',
    'product sticker design',
    'cover design',
    'packaging design',
  ],
};
