export const siteMetadata = {
  title: 'Krishna Chandra | Performance Engineering, Design & Digital Solutions',
  description:
    'Krishna Chandra delivers performance engineering, load testing, observability, creative design, website creation and Android app development.',
  url: 'https://krishnachandra.com',
  keywords: [
    'Krishna Chandra',
    'Krishna Chandra software engineer',
    'Krishna Chandra performance engineer',
    'Krishna Chandra performance testing engineer',
    'Krishna Chandra portfolio',
    'software engineer portfolio India',
    'performance engineer India',
    'performance testing consultant India',
    'load testing engineer',
    'application performance engineer',
    'enterprise performance engineering',
    'performance testing services',
    'performance test strategy',
    'load test planning',
    'stress testing',
    'endurance testing',
    'spike testing',
    'response time analysis',
    'throughput analysis',
    'bottleneck analysis',
    'application monitoring',
    'observability engineering',
    'cloud readiness assessment',
    'release readiness testing',
    'production performance testing',
    'performance test automation',
    'test automation engineer',
    'CI/CD performance testing',
    'performance test governance',
    'workload modelling',
    'workload model design',
    'realistic load testing',
    'JMeter expert',
    'Apache JMeter consulting',
    'JMeter performance testing',
    'JMeter test automation',
    'LoadRunner expert',
    'LoadRunner modernization',
    'LoadRunner performance testing',
    'Micro Focus LoadRunner',
    'performance test scripting',
    'API performance testing',
    'web application load testing',
    'mobile app performance testing',
    'database performance analysis',
    'SQL performance tuning',
    'Oracle performance testing',
    'Oracle Inform Suite performance engineering',
    'Oracle Enterprise Manager',
    'APM monitoring',
    'application performance monitoring',
    'infrastructure monitoring',
    'log analysis',
    'cloud performance engineering',
    'AWS performance testing',
    'Selenium testing',
    'Cucumber automation',
    'Java test automation',
    'performance engineering leadership',
    'engineering leadership',
    'software quality engineering',
    'quality assurance consulting',
    'digital transformation services',
    'technology consulting India',
    'Noida software engineer',
    'Delhi NCR performance engineer',
    'web development',
    'Android app development',
    'product sticker design',
    'cover design',
    'packaging design',
    'logo design services',
    'logo designer India',
    'business logo design',
    'custom logo design',
    'pamphlet design services',
    'brochure design services',
    'flyer design services',
    'print design services',
    'interior design concepts',
    'exterior design concepts',
    'commercial exterior design',
    'residential interior design',
    'website creation services',
    'responsive website design',
    'website development India',
    'business website design',
    'portfolio website development',
    'Android app development services',
    'Android app developer India',
    'mobile application development',
    'product label design',
    'cover design services',
    'book cover design',
    'packaging design services',
    'product packaging design',
    'creative design services',
    'digital design agency',
    'design and development services',
  ],
};
